# Adapted from https://github.com/JuliaCI/Appveyor.jl and https://github.com/starkat99/appveyor-rust

platform:
 - x64

# Only GNU is supported
environment:
  julia_version: 1
  JULIA_DIR: C:\julia
  CYGWIN_DIR: C:\cygwin64
  matrix:
    # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
    # Beta 64-bit GNU
    - channel: beta
      target: x86_64-pc-windows-gnu
    # Nightly 64-bit GNU
    - channel: nightly
      target: x86_64-pc-windows-gnu

matrix:
  allow_failures:
    - channel: nightly

install:
  # Install Julia
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
  # Install Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\julia\bin
  - rustc -vV
  - cargo -vV
  - git submodule update

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false

test_script:
  - cargo test --verbose -- --test-threads 1
