# Adapted from https://github.com/JuliaCI/Appveyor.jl and https://github.com/starkat99/appveyor-rust

platform:
 - x86
 - x64

# Only GNU is supported
environment:
  julia_version: 1
  JULIA_DIR: C:\julia
  matrix:
    # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
      CYGWIN_DIR: C:\cygwin64
    # Stable 32-bit GNU
    - channel: stable
      target: i686-pc-windows-gnu
      CYGWIN_DIR: C:\cygwin
    # Beta 64-bit GNU
    - channel: beta
      target: x86_64-pc-windows-gnu
      CYGWIN_DIR: C:\cygwin64
    # Beta 32-bit GNU
    - channel: beta
      target: i686-pc-windows-gnu
      CYGWIN_DIR: C:\cygwin
    # Nightly 64-bit GNU
    - channel: nightly
      target: x86_64-pc-windows-gnu
      CYGWIN_DIR: C:\cygwin64
    # Nightly 32-bit GNU
    - channel: nightly
      target: i686-pc-windows-gnu
      CYGWIN_DIR: C:\cygwin

matrix:
  exclude:
   - platform: x86
     target: x86_64-pc-windows-gnu
   - platform: x64
     target: i686-pc-windows-gnu
  allow_failures:
    - channel: nightly

install:
  # Install Julia
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
  # Install Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\julia\bin
  - rustc -vV
  - cargo -vV

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false

test_script:
  - cargo test --verbose -- --test-threads 1
