language: rust
sudo: required
dist: bionic
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.5.0-linux-x86_64.tar.gz -O /tmp/julia.tar.gz
  - tar -xvf /tmp/julia.tar.gz
  - export JULIA_DIR=$PWD/julia-1.5.0
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/julia-1.5.0/lib
  - export JLRS_ROOT=$TRAVIS_BUILD_DIR
script:
  - cargo build --verbose
  - cargo test --verbose -- --test-threads 1
branches:
  only:
    - master

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --exclude-files jl_sys/* --exclude-files jlrs_derive/* jl_sys/*  -- --test-threads 1
  fi