
[workspace]
members = [
    "jlrs",
    "jlrs_derive",
    "jlrs_derive_tests",
    "jlrs_async_tests",
    "jl_sys"
]

exclude = [
    "examples"
]

[profile.coverage]
panic = "abort"
opt-level = 0
overflow-checks = false
incremental = false
codegen-units = 1
inherits = "test"
