[package]
name = "jlrs"
version = "0.14.0"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
description = """
jlrs provides bindings to the Julia C API that enables Julia code to be called from Rust and more.
"""
documentation = "https://docs.rs/jlrs"
homepage = "https://github.com/Taaitaaiger/jlrs"
repository = "https://github.com/Taaitaaiger/jlrs"
readme = "../README.md"
keywords = ["Julia", "math", "mathematics", "bindings", "ffi"]
categories = ["api-bindings", "mathematics"]
license = "MIT"
edition = "2018"

[features]
default = ["prelude"]
sync-rt = []
async = ["futures", "crossbeam-channel", "async-trait"]
async-rt = ["async"]
async-std-rt = ["async-rt", "async-std"]
tokio-rt = ["async-rt", "tokio"]
jlrs-ndarray = ["ndarray"]
f16 = ["half"]
prelude = []
pyplot = []
internal-types = []
ccall = []
uv = ["jl-sys/uv", "ccall"]
debug = ["jl-sys/debug"]
docs = [
    "jl-sys/docs", "uv", "async-std-rt", "tokio-rt", "f16", "jlrs-ndarray", 
    "jlrs-derive", "sync-rt", "ccall", "internal-types", "pyplot"
]
lts = ["jl-sys/lts"]

[dependencies]
jl-sys = {version = "0.16", path = "../jl_sys" }
smallvec = "1"
jlrs-derive = { version = "0.4", optional = true, path = "../jlrs_derive" }
futures = { version = "0.3", optional = true }
crossbeam-channel = { version = "0.5", optional = true }
async-trait = { version = "0.1", optional = true }
async-std = { version = "1", features = ["unstable"], optional = true }
ndarray = { version = "0.15", optional = true }
half = { version = "1", optional = true }
tokio = { version = "1", optional = true, features = ["rt", "time", "sync"]}
cfg-if = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt", "time", "sync"]}

[package.metadata.docs.rs]
features = ["docs"]
