[package]
name = "jlrs"
version = "0.6.0"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
description = """
jlrs is a library built around bindings to the Julia C API that enables Julia code to be called 
from Rust. jlrs can move many kinds of data from Rust to Julia and back, share n-dimensional 
numerical arrays between languages, call arbitrary functions, and load code from arbitrary Julia
source files. jlrs currently supports Linux and Windows.
"""
documentation = "https://docs.rs/jlrs"
homepage = "https://github.com/Taaitaaiger/jlrs"
repository = "https://github.com/Taaitaaiger/jlrs"
readme = "../README.md"
keywords = ["Julia", "math", "mathematics", "bindings", "ffi"]
license = "MIT"
edition = "2018"

[features]
default = ["jlrs-derive"]
docs-rs = ["jl-sys/docs-rs", "jlrs-derive"]

[dependencies]
jl-sys = {version = "0.8", path = "../jl_sys" }
jlrs-derive = { version = "0.2", optional = true, path = "../jlrs_derive" }

[package.metadata.docs.rs]
features = ["docs-rs"]
