[package]
name = "jlrs"
version = "0.12.0"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
description = """
jlrs provides bindings to the Julia C API that enables Julia code to be called from Rust and more.
"""
documentation = "https://docs.rs/jlrs"
homepage = "https://github.com/Taaitaaiger/jlrs"
repository = "https://github.com/Taaitaaiger/jlrs"
readme = "../README.md"
keywords = ["Julia", "math", "mathematics", "bindings", "ffi"]
categories = ["api-bindings", "mathematics"]
license = "MIT"
edition = "2018"

[features]
default = ["jlrs-derive"]
uv = ["jl-sys/uv"]
async = ["futures", "crossbeam-channel", "async-trait", "async-std"]
jlrs-ndarray = ["ndarray"]
f16 = ["half"]
docs-rs = ["jl-sys/docs-rs", "jlrs-derive", "async", "jlrs-ndarray", "f16"]

[dependencies]
jl-sys = {version = "0.13", path = "../jl_sys" }
jlrs-derive = { version = "0.3", optional = true, path = "../jlrs_derive" }
smallvec = "1"
futures = { version = "0.3", optional = true }
crossbeam-channel = { version = "0.5", optional = true }
async-trait = { version = "0.1", optional = true }
async-std = { version = "1.9", features = ["unstable"], optional = true }
ndarray = { version = "0.15", optional = true }
half = { version = "1", optional = true }

[package.metadata.docs.rs]
features = ["docs-rs"]
