[package]
name = "jlrs"
version = "0.10.0"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
description = """
jlrs is a library built around bindings to the Julia C API that enables Julia code to be called 
from Rust. jlrs can move many kinds of data from Rust to Julia and back, share n-dimensional 
numerical arrays between languages, call arbitrary functions, and load code from arbitrary Julia
source files. jlrs currently supports Linux and Windows.
"""
documentation = "https://docs.rs/jlrs"
homepage = "https://github.com/Taaitaaiger/jlrs"
repository = "https://github.com/Taaitaaiger/jlrs"
readme = "../README.md"
keywords = ["Julia", "math", "mathematics", "bindings", "ffi"]
license = "MIT"
edition = "2018"

[features]
default = ["jlrs-derive"]
async = ["futures", "crossbeam-channel", "async-trait", "async-std"]
jlrs-ndarray = ["ndarray"]
f16 = ["half"]
coverage = []
docs-rs = ["jl-sys/docs-rs", "jlrs-derive", "async", "jlrs-ndarray"]

[dependencies]
jl-sys = {version = "0.11", path = "../jl_sys" }
jlrs-derive = { version = "0.2", optional = true, path = "../jlrs_derive" }
smallvec = "1"
futures = { version = "0.3", optional = true }
crossbeam-channel = { version = "0.5", optional = true }
async-trait = { version = "0.1", optional = true }
async-std = { version = "1.9", features = ["unstable"], optional = true }
ndarray = { version = "0.15", optional = true }
half = { version = "1", optional = true }

[package.metadata.docs.rs]
features = ["docs-rs"]
