[package]
name = "jl-sys"
version = "0.9.0"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
description = """
jl-sys contains the generated bindings for the Julia C API used by jlrs.
"""
documentation = "https://docs.rs/jl-sys"
homepage = "https://github.com/Taaitaaiger/jlrs"
repository = "https://github.com/Taaitaaiger/jlrs"
readme = "README.md"
keywords = ["Julia", "math", "mathematics", "bindings", "ffi"]
license = "MIT"
edition = "2018"
links = "julia"

[features]
docs-rs = []
dynamic = ["libc"]

[dependencies]
libc = { version = "0.2", optional = true }

[build-dependencies]
bindgen = "0.54.0"
syn = { version = "1", features = ["full", "parsing", "clone-impls", "printing", "extra-traits"] }
quote = "1"

[package.metadata.docs.rs]
features = ["docs-rs"]
