name: CI

on:
  push:
    branches: [ master, v0.8 ]
  pull_request:
    branches: [ master, v0.8 ]

  workflow_dispatch:

jobs:
  test-linux:
    env:
      JULIA_NUM_THREADS: 3
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      matrix:
        rust: [stable, beta]
        allow-fail: [false]
        include:
          - rust: nightly
            allow-fail: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1.4.1
        with:
          version: 1.5.3

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: |
          export JULIA_DIR="$(dirname $(dirname $(which julia)))"
          export LD_LIBRARY_PATH="${JULIA_DIR}/lib:${LD_LIBRARY_PATH}"
          cargo test --verbose -- --test-threads=1
          
  coverage:
    env:
      JULIA_NUM_THREADS: 3
    runs-on: ubuntu-latest
    needs: test-linux
    steps:
      - uses: actions/checkout@v2

      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1.4.1
        with:
          version: 1.5.3

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '--exclude-files examples/* --exclude-files jl_sys/* --exclude-files jlrs_derive/* jl_sys/*  -- --test-threads 1'

      - name: Set env
        run: |
          echo "JULIA_DIR=$(dirname $(dirname $(which julia)))" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${JULIA_DIR}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
