name: CI

on:
  push:
    branches: [ master, v0.10, dev ]
  pull_request:
    branches: [ master, v0.10, dev ]

  workflow_dispatch:

jobs:
  test-linux:
    env:
      JULIA_NUM_THREADS: 3
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      matrix:
        rust: [stable, beta]
        allow-fail: [false]
        include:
          - rust: nightly
            allow-fail: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: |
          export JULIA_DIR="$(dirname $(dirname $(which julia)))"
          export LD_LIBRARY_PATH="${JULIA_DIR}/lib:${LD_LIBRARY_PATH}"
          cargo test --features async,jlrs-ndarray,f16 --verbose -- --test-threads=1

  docs:
    runs-on: ubuntu-latest
    needs: test-linux
    steps:
      - uses: actions/checkout@v2

      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set env
        run: |
          export JULIA_DIR=$(dirname $(dirname $(which julia)))
          echo "LD_LIBRARY_PATH=${JULIA_DIR}/lib:${JULIA_DIR}/lib/julia:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
          echo "JULIA_DIR=${JULIA_DIR}" >> $GITHUB_ENV

      - name: Build Docs
        run: cargo doc
