name: CI

on:
  push:
    branches: [ master, v0.8 ]
  pull_request:
    branches: [ master, v0.8 ]

  workflow_dispatch:

jobs:
  setup:
    env:
     JULIA_NUM_THREADS: 3

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1.4.1
        with:
          version: 1.5.3

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm
  build:
    needs: setup
    steps:
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Run tests
        run: |
          export JULIA_DIR="$(dirname $(dirname $(which julia)))"
          export LD_LIBRARY_PATH="${JULIA_DIR}/lib:${LD_LIBRARY_PATH}"
          cargo test --verbose -- --test-threads=1
