[package]
name = "jlrs-async-tests"
version = "0.1.0"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
edition = "2018"

[features]
lts = []

[dependencies]
jlrs = { path = "../jlrs", features = ["async"] }
crossbeam-channel = "0.5"
